# Generated by Django 5.0.3 on 2024-05-01 13:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminID', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('admin_firstname', models.CharField(max_length=50)),
                ('admin_lastname', models.CharField(max_length=50)),
                ('admin_username', models.CharField(max_length=50)),
                ('admin_Email', models.CharField(max_length=254)),
                ('admin_password', models.CharField(max_length=50)),
                ('admin_Dateofbirth', models.DateField(default=django.utils.timezone.now)),
                ('admin_accountstatus', models.IntegerField(choices=[(0, 'Current'), (1, 'Blocked')], default=0)),
                ('admin_creationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_phoneNumber', models.CharField(blank=True, max_length=13)),
                ('admin_address', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipmentID', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('Equipmentname', models.CharField(max_length=50, verbose_name='Name')),
                ('Equipment_type', models.CharField(max_length=50, verbose_name='Type')),
                ('Equipment_category', models.CharField(choices=[('PC/Laptop', 'PC/Laptop'), ('VR-Headset', 'VR Headset'), ('Camera/Sensors', 'Camera/Sensors'), ('PC-Peripherals', 'PC Peripherals'), ('Furniture', 'Furniture'), ('Other', 'Other'), ('VR-Controller', 'VR Controller'), ('Phone/Tablets', 'Phone/Tablets'), ('Power/Cable', 'Power/Cable'), ('Non_PortablePC', 'NonPortablePC')], max_length=50, verbose_name='Category')),
                ('Equipment_lastUsed', models.DateTimeField(default=django.utils.timezone.now)),
                ('Equipment_warrantyinfo', models.DateTimeField(verbose_name='Warranty Info')),
                ('Equipment_assignedlocation', models.CharField(choices=[('Other', 'Other'), ('XR Lab', 'XR Lab'), ('XR Lab Blue Cabinet', 'XR Lab Blue Cabinet'), ('XR Lab Blue Cabinet Large', 'XR Lab Blue Cabinet Large'), ('XR medium wooden cabinet', 'XR medium wooden cabinet')], max_length=30, verbose_name='Assigned Location')),
                ('Equipment_restrictionStatus', models.IntegerField(choices=[(0, 'Anyone can use this'), (1, 'Can Only be Used by Staff and Admin')], verbose_name='Restriction')),
                ('Equipment_UsageType', models.IntegerField(choices=[(0, 'Can be Used and borrowed to home'), (1, 'Only used at University')], verbose_name='Take Home?')),
                ('Equipment_images', models.ImageField(upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(blank=True, default='DEFAULT VALUE', max_length=50)),
                ('user_firstname', models.CharField(max_length=50, verbose_name='First Name')),
                ('user_lastname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('user_Email', models.CharField(max_length=254, verbose_name='Email')),
                ('user_password', models.CharField(max_length=50)),
                ('user_Dateofbirth', models.DateField(verbose_name='Date of Birth')),
                ('user_accountstatus', models.IntegerField(choices=[(0, 'Current'), (1, 'Blocked')], default=0)),
                ('user_creationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_currentReservation', models.CharField(blank=True, max_length=50)),
                ('user_historicalreservation', models.CharField(blank=True, max_length=50)),
                ('user_phoneNumber', models.CharField(blank=True, max_length=13, verbose_name='Phone Number')),
                ('user_address', models.CharField(blank=True, max_length=50, verbose_name='Address')),
                ('userType', models.IntegerField(choices=[(0, 'User'), (1, 'Not User')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AdminandEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.admin')),
                ('Equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportKey', models.CharField(max_length=50, null=True)),
                ('lastgeneratedreport', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('Admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.admin')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='Report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.report'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingID', models.CharField(default='DEFAULT VALUE', max_length=50, null=True)),
                ('Booking_status', models.IntegerField(choices=[(0, 'Waiting for approval'), (1, 'Approved'), (2, 'Denied'), (3, 'Waiting to be collected'), (4, 'Collected'), (5, 'Not returned'), (6, 'Returned')], null=True)),
                ('Booking_alertstatus', models.IntegerField(null=True)),
                ('Booking_madeDate', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('Booking_startDate', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('Booking_endDate', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('Admin', models.ForeignKey(default='DEFAULT VALUE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.admin')),
                ('Equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coursework.equipment')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.user')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='Reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.reservation'),
        ),
        migrations.AddField(
            model_name='admin',
            name='Reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.reservation'),
        ),
        migrations.AddField(
            model_name='admin',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.user'),
        ),
    ]
