# Generated by Django 5.0.3 on 2024-04-15 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_firstname', models.CharField(max_length=50, null=True)),
                ('admin_lastname', models.CharField(max_length=50, null=True)),
                ('admin_username', models.CharField(max_length=50, null=True)),
                ('admin_Email', models.EmailField(max_length=254, null=True)),
                ('admin_password', models.CharField(max_length=50, null=True)),
                ('admin_Dateofbirth', models.DateField(auto_now=True, null=True)),
                ('admin_accountstatus', models.IntegerField(null=True)),
                ('admin_creationDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('admin_phoneNumber', models.IntegerField(verbose_name='')),
                ('admin_address', models.CharField(max_length=50, null=True)),
                ('userID', models.CharField(max_length=50, null=True)),
                ('adminID', models.CharField(max_length=50, null=True)),
                ('EquipmentID', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminandEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipmentID', models.CharField(max_length=50, null=True)),
                ('adminID', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipmentID', models.CharField(max_length=50, null=True)),
                ('Equipmentname', models.CharField(max_length=50, null=True)),
                ('Equipment_type', models.CharField(max_length=50, null=True)),
                ('Equipment_category', models.CharField(max_length=50, null=True)),
                ('Equipment_lastUsed', models.DateTimeField(auto_now_add=True, null=True)),
                ('Equipmment_warrantyinfo', models.DateTimeField(auto_now_add=True, null=True)),
                ('Equipment_assignedlocation', models.CharField(choices=[('XR Lab', 'XR Lab'), ('XR Lab Blue Cabinet', 'XR Lab Blue Cabinet'), ('XR Lab Blue Cabinet Large', 'XR Lab Blue Cabinet Large'), ('XR medium wooden cabinet', 'XR medium wooden cabinet')], max_length=30, null=True)),
                ('Equipment_restrictionStatus', models.IntegerField(choices=[(0, 'Option 0'), (1, 'Option 1')], null=True)),
                ('Equipment_UsageType', models.IntegerField(choices=[(0, 'Option 0'), (1, 'Option 1')], null=True)),
                ('Booking_alertstatus', models.IntegerField(choices=[(0, 'Option 0'), (1, 'Option 1')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportKey', models.CharField(max_length=50, null=True)),
                ('Booking_status', models.IntegerField(null=True)),
                ('lastgeneratedreport', models.DateTimeField(auto_now_add=True, null=True)),
                ('Booking_startDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('Booking_endDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('User_firstname', models.CharField(max_length=50, null=True)),
                ('User_lastname', models.CharField(max_length=50, null=True)),
                ('User_Email', models.EmailField(max_length=254, null=True)),
                ('User_Dateofbirth', models.DateField(auto_now=True, null=True)),
                ('User_phoneNumber', models.IntegerField(verbose_name='')),
                ('userID', models.CharField(max_length=50, null=True)),
                ('adminID', models.CharField(max_length=50, null=True)),
                ('BookingID', models.CharField(max_length=50, null=True)),
                ('Booking_alertstatus', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingID', models.CharField(max_length=50, null=True)),
                ('Booking_status', models.IntegerField(null=True)),
                ('Booking_alertstatus', models.IntegerField(null=True)),
                ('Booking_madeDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('Booking_startDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('Booking_endDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('User_firstname', models.CharField(max_length=50, null=True)),
                ('User_lastname', models.CharField(max_length=50, null=True)),
                ('User_Email', models.EmailField(max_length=254, null=True)),
                ('User_Dateofbirth', models.DateField(auto_now_add=True, null=True)),
                ('admin_phoneNumber', models.IntegerField(verbose_name='')),
                ('admin_address', models.CharField(max_length=50, null=True)),
                ('userID', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='User_Email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='RoleType',
            new_name='User_RoleType',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='accountstatus',
            new_name='User_accountstatus',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='User_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='creationDate',
            new_name='User_creationDate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='currentReservation',
            new_name='User_currentReservation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='User_firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='historicalreservation',
            new_name='User_historicalreservation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='User_lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='User_password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userType',
            new_name='User_phoneNumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Dateofbirth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='user',
            name='UserType',
            field=models.IntegerField(choices=[(0, 'Option 0'), (1, 'Option 1')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='User_Dateofbirth',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
