# Generated by Django 5.0.3 on 2024-04-15 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0004_rename_equipmment_warrantyinfo_equipment_equipment_warrantyinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.admin'),
        ),
    ]
