# Generated by Django 5.0.3 on 2024-04-15 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0005_user_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.equipment'),
        ),
    ]
