# Generated by Django 5.0.3 on 2024-04-15 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0006_reservation_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='Equipment',
        ),
        migrations.RemoveField(
            model_name='report',
            name='User',
        ),
        migrations.AddField(
            model_name='admin',
            name='Report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.report'),
        ),
        migrations.AddField(
            model_name='admin',
            name='Reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.reservation'),
        ),
        migrations.AlterField(
            model_name='adminandequipment',
            name='Admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.admin'),
        ),
        migrations.AlterField(
            model_name='adminandequipment',
            name='Equipment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.equipment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='Admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.admin'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Equipment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.equipment'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='User',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.admin'),
        ),
    ]
