# Generated by Django 5.0.3 on 2024-05-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0006_remove_admin_customer_remove_admin_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='Booking_alertstatus',
        ),
    ]
