# Generated by Django 5.0.3 on 2024-04-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0007_remove_report_equipment_remove_report_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminandequipment',
            name='EquipmentID',
        ),
        migrations.RemoveField(
            model_name='adminandequipment',
            name='adminID',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Booking_endDate',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Booking_startDate',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Booking_status',
        ),
    ]
