# Generated by Django 5.0.3 on 2024-04-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0009_alter_equipment_equipment_usagetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='User_RoleType',
        ),
        migrations.AddField(
            model_name='equipment',
            name='Equipment_images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_accountstatus',
            field=models.IntegerField(choices=[(0, 'Current'), (1, 'Blocked')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserType',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Not User')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_accountstatus',
            field=models.IntegerField(choices=[(0, 'Current'), (1, 'Blocked')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_phoneNumber',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
